title: Data Spaces for Sustainability and Resilience in Manufacturing
description: > # this means to ignore newlines until "baseurl:"
  Submit to the HICSS-56 Minitrack on Data Spaces for Sustainability and Resilience in Manufacturing!
baseurl: /HICSS-56-Data-Spaces-for-Sustainability # the subpath of your site, e.g. /blog
url: https://internet-of-production.github.io # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "css/2016_style/img/icon-large.png"

#social: 
#  name: Your Facebook Page
#  link: "https://www.facebook.com/"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2016_pages', '_2017_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#social:
#  - title: facebook
#    url: https://www.facebook.com
#  - title: twitter
#    url: https://twitter.com

title_image: "hicss-56.png"

# Build settings
markdown: kramdown
permalink: pretty